
export type Quote = {
  id: string;
  text: string;
};

export type QuoteCategory = {
  slug: string;
  title: string;
  description: string;
  quotes: Quote[];
  image: string;
};

export const QUOTE_DATA: QuoteCategory[] = [
  {
    slug: 'excellence',
    title: 'Excellence',
    description: "S'efforcer d'exceller en toutes choses",
    image: 'excellence-bg',
    quotes: [
      { id: 'ex1', text: "L’excellence n’est pas le perfectionnisme. Les perfectionnistes ignorent la grâce divine et se proposent de se substituer à Dieu" },
      { id: 'ex2', text: "L’excellence est la quête d’une utilisation optimale du potentiel reçu de Dieu et dont les résultats révèlent la gloire de Dieu et contribuent à notre épanouissement." },
      { id: 'ex3', text: "En sacrifiant la gloire de Dieu pour rechercher notre propre gloire, Dieu finira toujours par s’opposer à nous" },
      { id: 'ex4', text: "En voulant faire comme les autres, il est possible que nous n’y arrivions pas en raison de nos capacités limitées par rapport aux leurs ou alors que nous y arrivions facilement et ainsi nous n’utiliserons plus au maximum nos capacités" },
      { id: 'ex5', text: "Nos capacités et la mission attachée à notre vie sont les standards approuvés par Dieu pour savoir si on a excellé ou pas" },
      { id: 'ex6', text: "La duplication des résultats atteints par les autres n’a aucun rapport avec l’excellence" },
      { id: 'ex7', text: "Les dons reçus de Dieu n’ont pas vocation à être thésaurisés ; ils doivent être mis en exercice" },
      { id: 'ex8', text: "Toute personne vient au monde en ayant un potentiel d’excellence" },
      { id: 'ex9', text: "Notre responsabilité devant Dieu et les hommes est proportionnelle au dépôt qu’il a fait en nous" },
      { id: 'ex10', text: "Puisque Dieu n’attend pas de nous le même résultat, chacun devrait chercher à donner le meilleur de lui-même selon les capacités reçues" },
      { id: 'ex11', text: "En étant conscients que Dieu attend que chacun excelle dans son couloir, on ne devrait entretenir ni complexe ni jalousie" },
      { id: 'ex12', text: "La faible ou la non utilisation de nos capacités est un refus manifeste d’adorer notre créateur et un renoncement à notre propre épanouissement" },
      { id: 'ex13', text: "On ne peut pas être épanoui en n’étant pas excellent" },
      { id: 'ex14', text: "L’excellence est la résultante de l’utilisation optimale des atouts que Dieu nous a donnés" },
      { id: 'ex15', text: "La gloire de Dieu est le filtre pour tester l’authenticité de l’excellence" },
      { id: 'ex16', text: "Toute realisation qui exclut la gloire de Dieu ne peut pas être qualifiée d’excellence" },
      { id: 'ex17', text: "Tout prix qui nous pousserait à ne pas prendre soin de notre âme n’est pas digne d’être payé, fût-il dans la recherche de l’excellence" },
      { id: 'ex18', text: "Il existe un lien direct entre la sainteté, la productivité et l’excellence" },
      { id: 'ex19', text: "La réussite dépend de la combinaison de multiples aspects, négliger l’un d’eux pourrait empêcher d’y arriver" },
      { id: 'ex20', text: "Le succès selon Dieu signifie atteindre le but pour lequel il nous a placés sur terre" },
      { id: 'ex21', text: "Dans la vie, en voulant assumer la charge de Dieu, nous finirons dans la frustration. De même, en laissant à Dieu notre charge, nous serons désolés. Ainsi, soyons sûrs de bien faire notre part, celle de Dieu étant assurée. Voilà la voie du succès" },
      { id: 'ex22', text: "Une vie réussie est celle qui rend gloire à Dieu, réalise sa mission terrestre et procure du bonheur aux autres" },
      { id: 'ex23', text: "L’accomplissement dans la vie vient aussi du fait de satisfaire les besoins principaux avant les secondaires ; l’inverse ne produit qu’une illusion de joie" },
    ],
  },
  {
    slug: 'relations',
    title: 'Relations',
    description: 'Construire des relations saines',
    image: 'relationships-bg',
    quotes: [
      { id: 'rel1', text: "Les vrais amis ne se trahissent pas. Si nous valorisons notre relation, veillons à ne jamais trahir notre partenaire" },
      { id: 'rel2', text: "En toutes choses, il y a des limites qu’il ne faut pas briser au risque de se faire du mal ainsi qu’à d’autres personnes" },
      { id: 'rel3', text: "Dans la vie, il existe des personnes rencontrées et des personnes recherchées. Les premières sont pourvues par Dieu et indispensables pour notre destinée ; les secondes entrent dans notre vie par notre volonté et ne nous sont pas indispensables" },
      { id: 'rel4', text: "Le bien-être d’une relation n’exclut pas la survenance des conflits mais il inclut plutôt la capacité à résoudre ces derniers" },
      { id: 'rel5', text: "La vie a une dimension individuelle et collective, la qualité de cette dernière dépend de l’état de la première" },
      { id: 'rel6', text: "La bonne gestion du conflit dans une relation peut être un grand catalyseur de l’épanouissement de celle-ci. Comment y arriver ? Par le dialogue et une franche communication" },
      { id: 'rel7', text: "Pour qu’une relation soit exceptionnellement épanouie, il faut qu’elle n’ait aucune autre qui lui soit concurrente, à quelque point que ce soit" },
      { id: 'rel8', text: "La précision de l’objet d’une relation est une condition d’évaluation de son utilité et un garde-fou contre les débordements" },
      { id: 'rel9', text: "L’amour c’est mettre la raison de côté par moments. Sinon rien ne va marcher" },
      { id: 'rel10', text: "En face d’une personne en difficulté, notre seule présence suffit par moment puisqu’il nous est difficile voire impossible de la comprendre" },
      { id: 'rel11', text: "En accordant à une personne une place qu’elle ne mérite pas dans notre vie, le déséquilibre va s’en suivre" },
      { id: 'rel12', text: "Il est important que nous soyons sélectifs dans nos relations : nous devons avoir une bonne raison de maintenir chaque personne dans notre vie" },
      { id: 'rel13', text: "Les difficultés que nous détectons dans la vie des autres sont une alarme pour nous d’apprécier la grâce de Dieu dans notre vie et une invitation de prier pour eux" },
    ],
  },
  {
    slug: 'croissance-spirituelle',
    title: 'Croissance Spirituelle',
    description: 'Grandir dans la foi et la sagesse',
    image: 'spiritual-growth-bg',
    quotes: [
        { id: 'cs1', text: "Si on est d’accord que Dieu a multiples voies d’agir, c’est qu’il agit même par le silence ou par toutes les autres voies qui nous paraissent inconfortables. Soyons confiants !" },
        { id: 'cs2', text: "Les remords ressentis après un mauvais acte sont un reflet de l’état du cœur de Dieu au moment de l’acte. Dieu a un cœur. Soyons réfléchis" },
        { id: 'cs3', text: "La méditation n’est pas une tâche de la journée. Elle est plutôt le préalable pour commencer la journée" },
        { id: 'cs4', text: "En vivant l’intimité avec Dieu, on acquiert la puissance nécessaire pour faire face à toutes les ruses du diable" },
        { id: 'cs5', text: "Il faut veiller à ne pas discuter avec la Parole de Dieu, car à son tour elle pourra nous juger" },
        { id: 'cs6', text: "Il ne faut pas confondre la grâce de Dieu avec ses promesses. La première est imméritée, les secondes s’arrachent" },
        { id: 'cs7', text: "Il est dangereux de fixer son regard sur le canal de bénédiction plutôt qu’à la source. En effet, le canal peut être temporaire alors que la source est permanente" },
        { id: 'cs8', text: "Les sales coups de Satan sont toujours à un pas de notre désobéissance à Dieu. Les visitations divines sont accessibles à notre obéissance. Faisons le choix" },
        { id: 'cs9', text: "N’essayons jamais d’impressionner Dieu : en faisant de bonnes œuvres, nous ne sommes pas aimés plus que les autres" },
        { id: 'cs10', text: "Puisque Dieu est bon envers tous et que ses dons sont irrévocables, ses bénédictions ne sont donc pas une mesure indiquée de la bonne santé de notre relation avec Lui. Comment entretiens-tu ta relation avec Dieu ?" },
        { id: 'cs11', text: 'Puisque Dieu a aussi les attributs d’une personne, nous devons agir envers Lui en tant que des personnes raisonnables' },
        { id: 'cs12', text: 'Dieu a besoin que nous restions éveillés, car il prend les petits détails de notre vie pour en faire une grande histoire' },
        { id: 'cs13', text: 'Une histoire écrite par Dieu est la combinaison de beaucoup de petits détails évènementiels' },
        { id: 'cs14', text: 'Les tentations de Satan sont de simples invitations auxquelles nous avons le pouvoir de dire non' },
        { id: 'cs15', text: 'En collaborant avec Satan, nous retardons le processus de l’exaucement' },
        { id: 'cs16', text: 'Dieu a promis de nous bénir, nous avons la responsabilité de nous préparer à accueillir la bénédiction' },
        { id: 'cs17', text: 'Tout ce que nous recevons des hommes ne pourra durer aussi longtemps que ceux-là alors que ce que nous recevons de Dieu n’a pas de fin' },
        { id: 'cs18', text: 'Le plan parfait de Dieu pour notre vie demande de nous une collaboration permanente en vue d’une réalisation sans faille' },
        { id: 'cs19', text: 'Si les circonstances de la vie sont instables, notre stabilité doit reposer sur quelque chose de plus stable : la Parole de Dieu' },
        { id: 'cs20', text: 'La durabilité des résultats obtenus avec Dieu dépend de la constance dans notre obéissance à ses instructions' },
        { id: 'cs21', text: 'La Divine Grace (DG) est la source de toutes les grâces' },
        { id: 'cs22', text: 'Les actions de Dieu sont à finalités multiples, ne négligeons aucune de ses instructions car on ignore laquelle pourra nous propulser' },
        { id: 'cs23', text: 'Les promesses de Dieu sont comme les marchandises avec manuel d’utilisation. Sondons les Écritures' },
        { id: 'cs24', text: 'Après que Dieu nous ait béni, ne plaçons pas notre sécurité dans la bénédiction reçue, mais continuons à dépendre de Dieu lui-même' },
        { id: 'cs25', text: 'Notre dépendance de Dieu est confirmée lorsque nous renonçons à nos capacités avérées pour nous soumettre au plan inconnu de Dieu' },
        { id: 'cs26', text: 'Personne n’est éternel, mais les actes qu’on pose ont des implications éternelles. Quel héritage vas-tu léguer aux générations futures ?' },
        { id: 'cs27', text: 'La protection de Dieu est maximale et efficace, mais nous pouvons nous en priver par notre manque de vigilance' },
        { id: 'cs28', text: 'Nous demandons à Dieu d’améliorer notre situation ; et après qu’il l’ait fait, que faisons-nous ?' },
        { id: 'cs29', text: 'Le refus d’écouter la voix douce de Dieu nous expose à subir les ordres rudes de Satan' },
        { id: 'cs30', text: 'Les épreuves de la vie sont une belle opportunité de prouver notre fidélité à Dieu' },
        { id: 'cs31', text: 'L’une des finalités du péché c’est de détourner notre attention de l’essentiel afin de nous rendre improductifs' },
        { id: 'cs32', text: 'La DG donne des provisions quotidiennes, on doit les utiliser chaque jour' },
        { id: 'cs33', text: 'Si le Dieu du temps est aussi le Dieu du résultat, pourquoi ne Le louons-nous pas pendant le processus ? Pourquoi paniquons-nous jusqu’à ce que le résultat soit atteint ? Faisons confiance en Dieu' },
        { id: 'cs34', text: 'Dieu parle de plusieurs manières et insiste même. Il faut être attentif pour l’écouter et surtout obéir' },
        { id: 'cs35', text: 'La valeur d’une offrande ne s’évalue pas en termes de montant mais de la considération et prière accompagnant le geste' },
        { id: 'cs36', text: 'Tout ce qui porte la mission de Dieu jouit de la protection divine' },
        { id: 'cs37', text: 'L’adoration consiste aussi en l’utilisation optimale des capacités que Dieu nous a données' },
        { id: 'cs38', text: 'Dieu peut être le premier opposant à une action qui ne recherche pas sa gloire. Qu’est-ce qui motive tes actions ?' },
        { id: 'cs39', text: 'Nous ne devons pas mener une vie juste par crainte de la mort mais plutôt pour réjouir le cœur de Dieu.' },
        { id: 'cs40', text: 'Lorsque nous oublions que c’est la DG qui nous soutient, nous nous permettons toutes choses et c’est alors que nos faiblesses sont exposées' },
        { id: 'cs41', text: 'La sanctification c’est aussi une gestion du temps conforme aux priorités de Dieu' },
        { id: 'cs42', text: 'La vie d’obéissance nous permet d’expérimenter la providence de Dieu au quotidien' },
        { id: 'cs43', text: 'Lorsque notre vie réjouit le cœur de Dieu, il cherche également à nous faire du bien' },
        { id: 'cs44', text: 'L’obéissance à la voix de Dieu attire sur nous ses multiples bénédictions' },
        { id: 'cs45', text: 'Lorsque Dieu réalise ses promesses, évitons d’adopter des attitudes qui sèment la confusion et détournent notre attention' },
        { id: 'cs46', text: 'Si Dieu tient tellement à toi pour accomplir une mission, ce n’est pas qu’il manque qui utiliser. Il désire simplement déverser ses bénédictions dans ta vie.' },
        { id: 'cs47', text: 'Nous laisser conduire par l’Esprit de Dieu permet d’éviter les erreurs' },
        { id: 'cs48', text: 'Lorsque nos actions concordent avec le plan de Dieu pour notre vie, notre cœur est rempli de joie' },
        { id: 'cs49', text: 'À l’obéissance s’attache la bénédiction et à la désobéissance la malédiction. Chacun de nos choix a une conséquence' },
        { id: 'cs50', text: 'Lorsque nous servons Dieu avec entière dévotion, il ne manque jamais de manifester sa gloire' },
        { id: 'cs51', text: 'Les bénédictions de Dieu ne sont pas toujours surnaturelles, elles sont aussi naturelles' },
        { id: 'cs52', text: 'Dieu est bon envers toutes ses créatures, et fidèle envers ses enfants' },
        { id: 'cs53', text: 'Le monde ne donnera jamais de temps favorable pour communier avec le Créateur, chacun a la responsabilité de le créer' },
        { id: 'cs54', text: 'La bonté divine doit nous pousser à mener une vie juste et pleine de miséricorde envers les autres' },
        { id: 'cs55', text: 'La confiance en Dieu implique aussi la prise au sérieux de nos responsabilités grâce aux capacités reçues de Lui' },
        { id: 'cs56', text: 'La confiance que les gens placent en nous doit être un moyen de les orienter vers Dieu et non pas les maintenir focalisés sur nous' },
        { id: 'cs57', text: 'L’obéissance à la voix de Dieu nous épargnera des pièges et dangers qui se trouvent sur notre chemin' },
        { id: 'cs58', text: 'Il y a des choses que Dieu s’est déjà décidé d’opérer dans nos vies mais qui ne se produiront que lorsque nous prions' },
        { id: 'cs59', text: 'Notre sérieux avec Dieu profitera à nos proches : Noé survécut au déluge avec tous les membres de sa famille' },
        { id: 'cs60', text: 'Il ne faut pas se complaire dans les promesses de Dieu tout en faisant le mal' },
        { id: 'cs61', text: 'Lorsqu’on comprend que la DG (Divine Grace) ne consiste pas nécessairement à obtenir de Dieu ce qu’on veut, mais plutôt ce dont on a besoin, alors le cœur fait monter à Dieu d’innombrables actions de grâces mélangées de confessions' },
        { id: 'cs62', text: 'En comprenant que les promesses de DIEU sont toujours conditionnées, il est sage de chercher à remplir la condition plutôt que de rechercher la bénédiction' },
        { id: 'cs63', text: 'Qu’as-tu reçu de Dieu ? La qualité de ta vie est-elle proportionnelle à ce que Dieu t’a appris ?' },
        { id: 'cs64', text: 'La disposition que nous avons à aider les autres ne doit pas nous amener à manquer du temps à passer auprès de notre source : Dieu' },
        { id: 'cs65', text: 'Le refus de s’éloigner de la source de la tentation est une autre forme d’orgueil et expose à une ruine progressive' },
        { id: 'cs66', text: 'Toute planification faite avec Dieu finit par se réaliser au bon moment' },
        { id: 'cs67', text: 'Dieu peut permettre Satan de toucher à ce qui nous est cher pour éprouver notre foi, toutefois, il reste au contrôle' },
        { id: 'cs68', text: 'Lorsque nous témoignons ouvertement de notre foi, Dieu nous secourt afin de faire respecter son nom' },
        { id: 'cs69', text: 'Toute chose faite pour Christ sur la terre a une récompense éternelle' },
        { id: 'cs70', text: 'Dans le combat spirituel et dans la marche chrétienne en général, nous devons nous focaliser sur Dieu et non sur Satan' },
        { id: 'cs71', text: 'En n’étant pas prêt à payer le prix d’une repentance sincère, on finit toujours par tomber dans le même péché' },
        { id: 'cs72', text: 'Les plans de Dieu sont bons et immuables, seulement une vie de péché peut faire qu’on n’en jouisse pas' },
        { id: 'cs73', text: 'La communion fraternelle est une mesure de protection contre certaines attaques du diable' },
        { id: 'cs74', text: 'Notre dépendance à Dieu doit être permanente, tant dans les grandes que dans les petites batailles' },
        { id: 'cs75', text: 'Dieu répond toujours, mais très souvent, Il nous fait participer à la matérialisation de l’exaucement' },
        { id: 'cs76', text: 'Une personne qui demeure dans le péché décide délibérément de retarder la manifestation de sa destinée' },
        { id: 'cs77', text: 'L’abandon des œuvres de la chair n’est pas le signe de la maturité spirituelle ; c’est plutôt la constance dans la foi et la persévérance jusqu’à la fin qui en sont la preuve' },
        { id: 'cs78', text: 'Quel qu’en soit le prix, l’obéissance à Dieu vaut toujours la peine' },
        { id: 'cs79', text: 'L’obéissance a une double dimension : positive (les choses à faire) et négative (celles à ne pas faire). Nous devons y veiller' },
        { id: 'cs80', text: 'La désobéissance à la parole de Dieu est une preuve de manque de foi et nous fait perdre la faveur de Dieu' },
        { id: 'cs81', text: 'L’obéissance à Dieu est la condition de validité de tout ce qu’on peut faire pour Lui' },
        { id: 'cs82', text: 'Dieu est présent dans chaque situation, si nous y regardons de près, nous verrons que sa bonté et son contrôle sont stables' },
        { id: 'cs83', text: 'Le chrétien doit attendre l’accomplissement de la promesse dans la joie tout en restant dans la présence de Dieu' },
        { id: 'cs84', text: 'La recherche de Dieu doit être continuelle ; les supplications lui adressées doivent se poursuivre jusqu’à ce qu’il agisse' },
        { id: 'cs85', text: 'La confiance en Dieu suppose que nous n’avons que Lui comme première et dernière solution' },
        { id: 'cs86', text: 'Après avoir investi du temps dans la présence de Dieu, il faut veiller à ne pas écouter les voix qui tendent à négliger la puissance acquise' },
        { id: 'cs87', text: 'Croire que Dieu va agir avant de voir son action est la clé pour recevoir de Lui' },
        { id: 'cs88', text: 'Nous devons apprécier les circonstances de la vie à la lumière de la Parole de Dieu et de la révélation que nous avons de Lui' },
        { id: 'cs89', text: 'La conscience de l’omniscience de Dieu doit nous pousser à toujours être sincères avec Lui' },
        { id: 'cs90', text: 'Quand Dieu retarde l’accès à quelque chose, nous devons être très sage pour saisir ce qu’il souhaite nous enseigner pendant l’attente' },
        { id: 'cs91', text: 'Lorsqu’une situation nous pousse à prier plus intensément que d’habitude, nous devons être sages pour prier pour des choses qui vont au-delà de ladite situation' },
        { id: 'cs92', text: 'Certaines bénédictions de Dieu dans nos vies visent à renforcer notre confiance en Lui et nous donnent la force de vaincre le doute' },
        { id: 'cs93', text: 'Dieu a la capacité de réaliser nos souhaits par les voies jamais imaginées' },
        { id: 'cs94', text: 'Lorsque Dieu nous bénit, il s’assure que nous jouissions de toutes les bénédictions sans que les unes n’excluent les autres' },
        { id: 'cs95', text: 'Même lorsque le diable imite la puissance de Dieu, la supériorité divine reste constante' },
    ]
  },
  {
    slug: 'developpement-personnel',
    title: 'Développement Personnel',
    description: 'Amélioration continue de soi',
    image: 'personal-development-bg',
    quotes: [
        { id: 'dp1', text: "Dieu bénit les efforts et récompense le sacrifice" },
        { id: 'dp2', text: "La beauté, l’intelligence, … sont des valeurs objectives gracieusement distribuées par le Créateur. Si on les possède, il ne faut pas penser être le seul à en avoir ni croire en avoir plus que les autres. Demeure humble" },
        { id: 'dp3', text: "Les problèmes permanents exigent des solutions durables, permanentes. Ainsi, en ignorant que Dieu est la solution, tôt ou tard on finira dans la frustration et la désolation" },
        { id: 'dp4', text: "La sagesse vient des épreuves, en simulant ces dernières, on aura une sagesse simulée" },
        { id: 'dp5', text: "Autant que la lutte est permanente, autant doit être notre vigilance. Si on néglige les principes même pour un instant, on se rend vulnérable à la chute" },
        { id: 'dp6', text: "Une vérité n’est utile que dans la mesure où elle est appliquée" },
        { id: 'dp7', text: "Il existe une nuance entre le calme et le silence. Un homme calme est quiet alors qu’on peut être silencieux tout en étant troublé" },
        { id: 'dp8', text: "C’est la radicalité de la méthode qui garantit la précision des résultats" },
        { id: 'dp9', text: "La répétition des erreurs est une voie de perdre son temps et détruire sa propre destinée" },
        { id: 'dp10', text: "L’énergie n’est utile que dans la mesure où elle nous aide à avancer. Or la prière est la plus grande source de puissance. Qu’en fais-tu ?" },
        { id: 'dp11', text: 'Le rachat de temps n’a rien à voir avec le remplissage de l’agenda, il consiste plutôt à réaliser à temps ce que Dieu attend de nous' },
        { id: 'dp12', text: 'En possédant une chose à laquelle quiconque peut avoir accès, nous n’avons aucune raison d’être orgueilleux. Restons humbles.' },
        { id: 'dp13', text: 'Toute chose acquise avant son temps idéal ne pourra procurer qu’une satisfaction illusoire. Soyons patients.' },
        { id: 'dp14', text: 'Les erreurs ne sont utiles dans la vie que si nous appliquons les leçons qu’elles nous ont apprises. Autrement, elles sont un frein à la réalisation de la destinée' },
        { id: 'dp15', text: 'À l’impossibilité d’annuler les plans de Dieu pour nos vies, Satan fera tout son possible pour les retarder, à condition que nous le lui permettions' },
        { id: 'dp16', text: 'Le corps humain a vocation à se détériorer avec le temps, il doit ainsi servir à laisser de bonnes empreintes' },
        { id: 'dp17', text: 'L’utilité d’un acte dépend du moment où il est posé ainsi que de conséquences qu’il engendre' },
        { id: 'dp18', text: 'Personne ne peut accomplir toute la volonté de Dieu, surtout que Dieu n’attend pas de nous toutes choses, mais quelques-unes.' },
        { id: 'dp19', text: 'Le travail et la prière nous font jouir des bénédictions de Dieu, la sanctification nous aide à les conserver et le péché nous les fait perdre' },
        { id: 'dp20', text: 'Avant d’accorder son temps aux choses scandaleuses, il faut penser aux tâches essentielles non encore réalisées' },
        { id: 'dp21', text: 'La pratique du péché est un puissant retardateur de destinée de la vie d’un homme' },
        { id: 'dp22', text: 'Nous avons tous une énergie limitée, mais à des quantités différentes. Nous devons l’utiliser rationnellement' },
        { id: 'dp23', text: 'Dieu ne cautionne pas des attitudes irresponsables, à nuancer avec sa miséricorde' },
        { id: 'dp24', text: 'Toute gentillesse de notre part qui facilite d’autres de bloquer notre épanouissement est une forme de manipulation. Il faut s’en libérer !' },
        { id: 'dp25', text: 'La cupidité nous entraine dans certains pièges, la sobriété nous évite certaines erreurs' },
        { id: 'dp26', text: 'Le destin existe, mais nous pouvons le rater si nous posons des actes le contrariant. Il est donc sage de veiller à nos actes qui peuvent soit confirmer ou annuler notre destin' },
        { id: 'dp27', text: 'La prévalence du mal n’est pas une excuse pour cesser à faire du bien' },
        { id: 'dp28', text: 'La discipline consiste à exécuter plusieurs tâches sans intervertir leur ordre d’importance' },
        { id: 'dp29', text: 'Le temps d’attente d’une chose doit être utilisé dans l’acquisition de la sagesse nécessaire en vue de la conservation de ladite chose' },
        { id: 'dp30', text: 'Il est utile de regretter ses erreurs, toutefois le temps de regret ne doit pas être si long qu’on soit bloqué de poursuivre son chemin' },
        { id: 'dp31', text: 'Dans toutes choses, il y a une dose du fanatisme qui ne doit toutefois pas primer sur les critères objectifs' },
        { id: 'dp32', text: 'L’impréparation et la non-reconnaissance d’une opportunité peuvent ruiner une destinée' },
        { id: 'dp33', text: 'Une vie empreinte de valeurs n’est pas épargnée de tentations, mais il est préférable de choisir de ne pas céder' },
        { id: 'dp34', text: 'Toute motivation peut être source d’auto destruction lorsqu’elle exalte l’égo au point de faire oublier que c’est Dieu la source' },
        { id: 'dp35', text: 'Le retard d’acquérir certaines choses vise de fois notre protection' },
        { id: 'dp36', text: 'Dans tous les domaines, la négligence des vérités de base est la cause de grandes chutes Revoyons nos fondamentaux !' },
        { id: 'dp37', text: 'Pour bien de choses, la fragilité révèle leur préciosité et invite donc l’apport d’un plus grand soin' },
        { id: 'dp38', text: 'Le repos est une étape essentielle du travail, car il nous permet de travailler encore' },
        { id: 'dp39', text: 'La vie est une vraie course non pas avec les autres, mais avec soi-même face aux objectifs que Dieu a assignés à chacun' },
        { id: 'dp40', text: 'Il existe plusieurs manières par lesquelles on perd le temps, mais la pire c’est d’être loin de Dieu. Es-tu en train de maximiser le temps ?' },
        { id: 'dp41', text: 'Planifier la journée est un garde-fou contre les malheurs du hasard. Tiens à tes programmes' },
        { id: 'dp42', text: 'En posant les actes moins réfléchis au motif qu’on a la maîtrise de la situation, on risque de se rendre compte plus tard qu’on en avait aucun contrôle' },
        { id: 'dp43', text: 'Toute bonne intention suivie d’un acte contradictoire produira un effet décevant' },
        { id: 'dp44', text: 'Toutes les actions de Satan à notre encontre visent à nous éloigner de Dieu, à nous dépouiller de grâces et à détruire notre destinée' },
        { id: 'dp45', text: 'Il faut nuancer entre le plaisir et l’accomplissement ; le premier est éphémère alors que le second est durable' },
        { id: 'dp46', text: 'En travaillant avec objectif et selon un programme, on peut atteindre la productivité et s’autoévaluer' },
        { id: 'dp47', text: 'La recherche du plaisir par des voies qui n’honorent pas Dieu peut conduire à un discrédit public et à une ruine de la destinée' },
        { id: 'dp48', text: 'Les promesses de Dieu sont gratuites. Si la jouissance de certaines d’entre elles dépend simplement de la foi, pour d’autres, il nous faut aussi un esprit de travail' },
        { id: 'dp49', text: 'Dieu honore les décisions qui sont prises sur base de la foi' },
        { id: 'dp50', text: 'L’application rapide des leçons que Dieu nous apprend est la condition pour passer au niveau supérieur' },
        { id: 'dp51', text: 'La duplicité d’un homme réduit son impact quel que soit son domaine' },
        { id: 'dp52', text: 'Quand nos actes sont en contradiction avec ce que nous demandons à Dieu, il est certain que nous ne recevrons rien, sous réserve de la bonté souveraine de Dieu' },
        { id: 'dp53', text: 'De même que les grandes chutes dans la vie procèdent de la négligence des principes de base, de même les scandales spirituels procèdent de la négligence de disciplines élémentaires : la prière et la méditation' },
        { id: 'dp54', text: 'Si Dieu nous bénit selon notre demande et que nous décidions de nous éloigner de lui par la suite pensant que nous avons la capacité de conserver la bénédiction reçue, comment pouvons-nous être qualifiés ?' },
        { id: 'dp55', text: 'Dans bien de cas, la volonté de Dieu n’est pas contraire à l’ordre naturel des choses car il est le Maître de la nature' },
        { id: 'dp56', text: 'La conscience de l’imminence de la fin du monde doit nous rendre sobres et sages' },
        { id: 'dp57', text: 'Toute personne qui ne glorifie pas Dieu dans son corps, a contrario, glorifie Satan' },
        { id: 'dp58', text: 'La complaisance et la fausse compassion sont des ennemis de la destinée' },
        { id: 'dp59', text: 'Il ne faut jamais chercher à être une solution temporaire à un problème qui nécessite un remède permanent et définitif' },
        { id: 'dp60', text: 'L’une des formes le plus fatales de l’orgueil consiste à corriger la parole de Dieu' },
        { id: 'dp61', text: 'De fois, nos vies ne brillent pas par l’imprécision de ce que nous voulons réellement' },
        { id: 'dp62', text: 'La persistance de certains défis dans nos vies est une invitation à monter de dimension' },
        { id: 'dp63', text: 'Tout succès que nous connaissons dans la vie est une occasion en or que Dieu nous donne pour Le présenter au monde' },
        { id: 'dp64', text: 'Une personne intelligente aux yeux de Dieu est celle qui ne peut pas utiliser ses capacités pour défier Dieu en détruisant son œuvre ou en contredisant ses valeurs' },
        { id: 'dp65', text: 'Les œuvres exceptionnelles réalisées par les enfants de Dieu pousseront les non-chrétiens de confesser Dieu de leur bouche' },
        { id: 'dp66', text: 'Le Saint-Esprit ne se limite pas seulement à la spiritualité ; il peut apporter son aide dans tous les domaines' },
    ]
  }
];

// Combine all quotes for daily quote and recently viewed logic
export const ALL_QUOTES: (Quote & { categorySlug: string })[] = QUOTE_DATA.flatMap(category => 
  category.quotes.map(quote => ({ ...quote, categorySlug: category.slug }))
);
